### ISSUE TITLE
無法下在orange3的漢化版

### ISSUE THREAD

**Issue by huginwu** [gengyabc/gengyabc.github.io#1]
點選下載後出現百度硬碟無資料,請問要去何處下載。謝謝

**Comment by zy-tech** [comment]
进入链接后有一个文件夹：“橙现智能”，点击进入后，看到几个文件夹，你是 win 系统就进入 win，你是 mac 系统就进入 mac，然后下载即可

**Comment by huginwu** [comment]
Sorry,因檫M入dc後,在百度dP中是@示所L的面已不存在,所以o法下d,麻┠,多x感恩

|翰
0952-112-842
B.R
祝您有美好的一天

寄件者: ***@***.***>
魉rg: 2021年4月1日 下午 02:10
收件者: ***@***.***>
副本: ***@***.***>; ***@***.***>
主旨: Re: [gengyabc/gengyabc.github.io] o法下在orange3的h化版 (#1)


进入链接后有一个文件夹：“橙现智能”，点击进入后，看到几个文件夹，你是 win 系统就进入 win，你是 mac 系统就进入 mac，然后下载即可

―

**Comment by zy-tech** [comment]
你试试这个二维码可以吗？大陆以为地区百度网盘好像有问题

![image](https://user-images.githubusercontent.com/54013300/113812333-7e08ce80-97a0-11eb-87cc-5fb6f951004c.png)

**Comment by huginwu** [comment]
多x提供Y,正在克服]园俣冗@P,多x

|翰
0952-112-842
B.R
祝您有美好的一天

寄件者: ***@***.***>
魉rg: 2021年4月7日 下午 12:55
收件者: ***@***.***>
副本: ***@***.***>; ***@***.***>
主旨: Re: [gengyabc/gengyabc.github.io] o法下在orange3的h化版 (#1)


你试试这个二维码可以吗？大陆以为地区百度网盘好像有问题

[image]<https://user-images.githubusercontent.com/54013300/113812333-7e08ce80-97a0-11eb-87cc-5fb6f951004c.png>

―

**Comment by zy-tech** [comment]
或者试试 dropbox 这个链接，我刚上传：https://www.dropbox.com/sh/qwb70p9e1pa5yq4/AAAt3_ANule2E6lofVt5tMKfa?dl=0

**Comment by huginwu** [comment]
安b中,改天有空的r候砗煤醚芯,在是太感恩大大的o私,感恩

|翰
0952-112-842
B.R
祝您有美好的一天

寄件者: ***@***.***>
魉rg: 2021年4月14日 下午 02:51
收件者: ***@***.***>
副本: ***@***.***>; ***@***.***>
主旨: Re: [gengyabc/gengyabc.github.io] o法下在orange3的h化版 (#1)


或者试试 dropbox 这个链接，我刚上传：https://www.dropbox.com/sh/qwb70p9e1pa5yq4/AAAt3_ANule2E6lofVt5tMKfa?dl=0

―

**Comment by huginwu** [comment]
很抱歉麻┠了,drobox上的n案是不是mac的版本,我後碛win10怎釉^安b都o法安b, D:\tool\橙现智能\Orange3-3.27.3,@嚎sn解_後也o法跑入安b面,cxOrange@BY也o反,麻┠了,多x感恩

|翰
0952-112-842
B.R
祝您有美好的一天

寄件者: ***@***.***>
魉rg: 2021年4月20日 上午 10:47
收件者: ***@***.***>
副本: ***@***.***>; ***@***.***>
主旨: Re: [gengyabc/gengyabc.github.io] o法下在orange3的h化版 (#1)


Closed #1<https://github.com/gengyabc/gengyabc.github.io/issues/1>.

―

**Comment by gengyabc** [comment]
你的回复乱码太多，我看不懂了，😭

**Comment by huginwu** [comment]
[Image]

我把我的問題用圖片檔貼給你，麻煩你了，多謝

取得 Android 版 Outlook<https://aka.ms/ghei36>
________________________________

**Comment by gengyabc** [comment]
看不到图片啊，😭

**Comment by huginwu** [comment]
我再處理了一次，很抱歉麻煩你了，多謝你的協助
________________________________
寄件者: gengyabc ***@***.***>
寄件日期: 2021年4月28日 下午 02:10
收件者: gengyabc/gengyabc.github.io ***@***.***>
副本: huginwu ***@***.***>; Author ***@***.***>
主旨: Re: [gengyabc/gengyabc.github.io] 無法下在orange3的漢化版 (#1)


看不到图片啊，😭
